from typing import Any, Dict, Optional

import json
import time
from pathlib import Path

from araras.notifications.email import send_email
from . import monitoring as _mon

from araras.utils.verbose_printer import VerbosePrinter

vp = VerbosePrinter()

_TEMPLATE_RECIPIENTS = {
    "emails": [
        "first-recipient@example.com",
        "second-recipient@example.com",
        "third-recipient@example.com",
    ]
}
_TEMPLATE_CREDENTIALS = {
    "email": "THE BOT EMAIL GOES HERE (YOU CAN USE app password FROM GMAIL TO CREATE A BOT ACCOUNT)",
    "password": "THE BOT PASSWORD GOES HERE",
}


class ConsolidatedEmailManager:
    """Handles consolidated email notifications with retry logic."""

    __slots__ = (
        "recipients_file",
        "credentials_file",
        "email_enabled",
        "retry_attempts",
        "retry_count",
        "last_notification_time",
        "restart_email_warning",
    )

    def __init__(
        self,
        recipients_file: Optional[str] = None,
        credentials_file: Optional[str] = None,
        retry_attempts: int = 2,
        restart_email_warning: bool = True,
    ) -> None:
        """Initialize the manager and validate configuration.

        Args:
            recipients_file (Optional[str]): Path to the JSON file containing the list of email
                recipients. Defaults to ``"./json/recipients.json"`` when not
                provided.
            credentials_file (Optional[str]): Path to the JSON file with the SMTP credentials.
                Defaults to ``"./json/credentials.json"``.
            retry_attempts (int): Maximum number of retries to attempt before giving
                up on sending a notification.
            restart_email_warning (bool): When ``True`` restart success and failure
                messages are sent via email.

        Notes:
            The configuration files are validated for existence and for the
            placeholder template content generated by the monitor launcher. If
            the files are missing, malformed, or still match the shipped
            templates, email alerts remain disabled until the user provides
            real values.
        """
        self.recipients_file = recipients_file or "./json/recipients.json"
        self.credentials_file = credentials_file or "./json/credentials.json"
        self.retry_attempts = retry_attempts
        self.email_enabled = self._validate_email_config()
        self.restart_email_warning = restart_email_warning
        self.retry_count = 0
        self.last_notification_time = 0

    def _load_json_config(self, file_path: str) -> Dict[str, Any]:
        """Read and parse a JSON configuration file.

        Args:
            file_path (str): Absolute or relative path to a JSON file. The file
                must exist and contain a top-level JSON object because the email
                configuration loader expects named keys such as ``emails``,
                ``email``, and ``password``. If the file contains another JSON
                type, the configuration is considered invalid and email is
                disabled explicitly.

        Returns:
            Dict[str, Any]: Parsed JSON object from the provided file.

        Raises:
            OSError: If the file cannot be opened.
            json.JSONDecodeError: If the file contents are not valid JSON.
            ValueError: If the top-level JSON value is not an object.
        """
        with open(file_path) as file_pointer:
            data = json.load(file_pointer)

        if not isinstance(data, dict):
            raise ValueError(f"Email config file must contain a JSON object: {file_path}")

        return data

    def _contains_template_placeholders(
        self,
        recipients_data: Dict[str, Any],
        credentials_data: Dict[str, Any],
    ) -> bool:
        """Return whether the email configuration still matches the templates.

        Args:
            recipients_data (Dict[str, Any]): Parsed ``recipients.json``
                content. If the dictionary matches the shipped template exactly,
                the monitor treats the file as unconfigured and keeps email
                disabled. Any user edit, even a single recipient change,
                prevents a template match on this branch.
            credentials_data (Dict[str, Any]): Parsed ``credentials.json``
                content. If the dictionary matches the shipped template exactly,
                email stays disabled because the placeholder sender and password
                cannot be used for SMTP authentication.

        Returns:
            bool: ``True`` when either JSON file still matches the launcher
            template, otherwise ``False``.
        """
        return recipients_data == _TEMPLATE_RECIPIENTS or credentials_data == _TEMPLATE_CREDENTIALS

    def _validate_email_config(self) -> bool:
        """Check that required email configuration files are usable.

        Returns:
            bool: ``True`` if both files exist, parse correctly, and no longer
            contain the shipped placeholder template values. ``False`` if the
            files are missing, malformed, or still unconfigured.

        Notes:
            The monitor intentionally disables email before the first send
            attempt so users receive an explicit warning as soon as template
            files are generated or invalid JSON is detected.
        """
        recipients_exists = Path(self.recipients_file).exists()
        credentials_exists = Path(self.credentials_file).exists()

        if not (recipients_exists and credentials_exists):
            vp.logf(
                f"Email config files not found: {self.recipients_file}, {self.credentials_file}, email alerts disabled",
                log_level="WARNING",
                tag=vp.gen_tag(),
                color="yellow",
            )
            return False

        try:
            recipients_data = self._load_json_config(self.recipients_file)
            credentials_data = self._load_json_config(self.credentials_file)
        except (OSError, ValueError, json.JSONDecodeError) as error:
            vp.logf(
                f"Email config files are invalid: {error}. Email alerts disabled until the JSON files are fixed.",
                log_level="WARNING",
                tag=vp.gen_tag(),
                color="yellow",
            )
            return False

        # The launcher can create placeholder JSON files automatically. The
        # monitor must treat those templates as disabled email configuration so
        # the first monitored run does not attempt to send with fake data.
        if self._contains_template_placeholders(recipients_data, credentials_data):
            vp.logf(
                "Email config files still contain template placeholders. "
                "Update recipients.json and credentials.json to enable email alerts.",
                log_level="WARNING",
                tag=vp.gen_tag(),
                color="yellow",
            )
            return False

        return True

    def send_consolidated_status_email(self, status_type: str, process_data: Dict[str, Any]) -> None:
        """Send a single consolidated status email.

        Args:
            status_type (str): Type of status message to send. Supported values are
                ``"restart_success"``, ``"scheduled_restart_success"``,
                ``"memory_aware_scheduled_restart_success"``,
                ``"restart_failed"``, ``"task_complete"`` and
                ``"memory_leak_warning"``.
            process_data (Dict[str, Any]): Dictionary with details about the process.  The
                expected keys vary depending on ``status_type``.

        Returns:
            None: A supported enabled notification is attempted; unsupported
            or disabled notifications return without delivery.

        Raises:
            RuntimeError: Not raised. Message construction and delivery errors
                are caught and reported.
        """
        if not self.email_enabled:
            return

        if not self.restart_email_warning and status_type in {
            "restart_success",
            "scheduled_restart_success",
            "memory_aware_scheduled_restart_success",
            "restart_failed",
        }:
            return

        try:
            timestamp = time.strftime("%Y-%m-%d %H:%M:%S %Z", time.localtime())
            title = process_data.get("title", "Unknown Process")
            inline_png = None

            if status_type == "restart_success":
                subject = f"{title} crashed - Restart Successful"
                color = "#28a745"
                status_title = "Process Restart Successful"
                status_description = "Process crashed but was successfully restarted"
                details_section = _mon.RESTART_DETAILS_TEMPLATE.format(
                    old_pid=process_data.get("old_pid", "N/A"),
                    new_pid=process_data.get("new_pid", "N/A"),
                    restart_count=process_data.get("restart_count", 0),
                    runtime=process_data.get("runtime", 0.0),
                )
            elif status_type == "scheduled_restart_success":
                subject = f"{title} - Scheduled Restart Successful"
                color = "#28a745"
                status_title = "Scheduled Restart Successful"
                status_description = "Process reached its configured interval and restarted successfully"
                details_section = _mon.SCHEDULED_RESTART_DETAILS_TEMPLATE.format(
                    old_pid=process_data["old_pid"],
                    new_pid=process_data["new_pid"],
                    scheduled_restart_count=process_data["scheduled_restart_count"],
                    interval_minutes=process_data["interval_seconds"] / 60.0,
                    runtime=process_data["runtime"],
                )
                inline_png = process_data["graph_png"]
            elif status_type == "memory_aware_scheduled_restart_success":
                subject = f"{title} - Memory-Aware Restart Successful"
                color = "#28a745"
                status_title = "Memory-Aware Restart Successful"
                status_description = (
                    "Process-tree RSS reached its configured threshold and the process restarted successfully"
                )
                inline_png = process_data.get("graph_png")
                graph_section = (
                    '<img src="cid:monitor-graph" alt="Previous process-tree RAM over time" '
                    'style="max-width:100%;height:auto" />'
                    if inline_png is not None
                    else ""
                )
                details_section = _mon.MEMORY_AWARE_SCHEDULED_RESTART_DETAILS_TEMPLATE.format(
                    old_pid=process_data["old_pid"],
                    new_pid=process_data["new_pid"],
                    scheduled_restart_count=process_data["scheduled_restart_count"],
                    current_rss_gib=process_data["current_rss_bytes"] / float(1024**3),
                    threshold_gib=process_data["threshold_bytes"] / float(1024**3),
                    poll_minutes=process_data["poll_interval_seconds"] / 60.0,
                    runtime=process_data["runtime"],
                    graph_section=graph_section,
                )
            elif status_type == "restart_failed":
                failed_attempts = process_data.get("failed_attempts", 0)
                remaining = process_data.get("remaining_attempts", 0)

                if remaining > 0:
                    subject = f"{title} crashed - Restart Failed ({failed_attempts} attempts, {remaining} remaining)"
                    status_description = (
                        f"Restart failed after {failed_attempts} attempts, {remaining} attempts remaining"
                    )
                else:
                    subject = f"{title} crashed - Maximum Restarts Reached"
                    status_description = "All restart attempts have been exhausted"

                color = "#dc3545"
                status_title = "Process Restart Failed"
                details_section = _mon.FAILURE_DETAILS_TEMPLATE.format(
                    failed_attempts=failed_attempts,
                    remaining_attempts=remaining,
                    restart_count=process_data.get("restart_count", 0),
                    error=process_data.get("error", "Unknown error"),
                )
            elif status_type == "task_complete":
                subject = f"{title} - Task Completed Successfully"
                color = "#28a745"
                status_title = "Task Completed Successfully"
                status_description = "Process completed all tasks successfully"
                details_section = _mon.COMPLETION_DETAILS_TEMPLATE.format(
                    restart_count=process_data.get("restart_count", 0),
                    scheduled_restart_count=process_data.get("scheduled_restart_count", 0),
                    total_restarts=process_data.get("restart_count", 0)
                    + process_data.get("scheduled_restart_count", 0),
                    total_runtime=process_data.get("total_runtime", 0.0),
                )
            elif status_type == "memory_leak_warning":
                subject = f"Possible Memory Leak Detected: {title}"
                color = "#b54708"
                status_title = "Possible Memory Leak Detected"
                status_description = (
                    "Sustained process-tree RSS growth matched the conservative warning rule"
                )
                details_section = _mon.MEMORY_LEAK_DETAILS_TEMPLATE.format(
                    pid=process_data["pid"],
                    current_rss_mib=process_data["current_rss_mib"],
                    net_growth_mib=process_data["net_growth_mib"],
                    slope_mib_per_minute=process_data["slope_mib_per_minute"],
                    r_squared=process_data["r_squared"],
                    warmup_minutes=process_data["warmup_seconds"] / 60.0,
                    window_minutes=process_data["window_seconds"] / 60.0,
                )
                inline_png = process_data["graph_png"]
            else:
                return

            html_content = _mon.CONSOLIDATED_STATUS_TEMPLATE.format(
                color=color,
                status_title=status_title,
                title=title,
                status_description=status_description,
                timestamp=timestamp,
                details_section=details_section,
            )

            if inline_png is None:
                send_email(
                    subject,
                    html_content,
                    self.recipients_file,
                    self.credentials_file,
                    "html",
                )
            else:
                send_email(
                    subject,
                    html_content,
                    self.recipients_file,
                    self.credentials_file,
                    "html",
                    inline_png=inline_png,
                )
            self.last_notification_time = time.time()
        except Exception as e:
            _mon.print_error_message("EMAIL", f"Failed to send consolidated status email: {e}")

    def should_attempt_restart(self, title: str, restart_count: int, max_restarts: int) -> bool:
        """Determine whether another restart attempt should be made.

        Args:
            title (str): The process title used for email notifications.
            restart_count (int): How many times the process has already been restarted.
            max_restarts (int): Maximum allowed restarts overall.

        Returns:
            bool: ``True`` if another restart should be attempted, ``False`` otherwise.

        Notes:
            If the internal retry counter exceeds ``retry_attempts`` this method
            will send a failure notification and reset the counter.
        """
        if self.retry_count < self.retry_attempts:
            self.retry_count += 1
            return True

        remaining_attempts = max(0, max_restarts - restart_count)
        self.send_consolidated_status_email(
            "restart_failed",
            {
                "title": title,
                "failed_attempts": self.retry_attempts,
                "remaining_attempts": remaining_attempts,
                "restart_count": restart_count,
                "error": f"Process failed to restart after {self.retry_attempts} retry attempts",
            },
        )

        self.retry_count = 0
        return remaining_attempts > 0

    def report_successful_restart(
        self,
        title: str,
        old_pid: int,
        new_pid: int,
        restart_count: int,
        runtime: float,
    ) -> None:
        """Report that a crashed process was successfully restarted."""
        self.retry_count = 0
        self.send_consolidated_status_email(
            "restart_success",
            {
                "title": title,
                "old_pid": old_pid,
                "new_pid": new_pid,
                "restart_count": restart_count,
                "runtime": runtime,
            },
        )

    def report_successful_scheduled_restart(
        self,
        title: str,
        old_pid: Optional[int],
        new_pid: int,
        scheduled_restart_count: int,
        runtime: float,
        interval_seconds: float,
        graph_png: bytes,
    ) -> None:
        """Report that an intentional scheduled restart succeeded.

        Args:
            title (str): Human-readable monitored process title.
            old_pid (int): PID intentionally stopped at the end of the
                interval.
            new_pid (int): Replacement PID that is running and monitored.
            scheduled_restart_count (int): Number of successful scheduled
                restarts including this transition.
            runtime (float): Runtime of the stopped process in seconds.
            interval_seconds (float): Positive configured scheduled interval
                in seconds.
            graph_png (bytes): Non-empty process-tree RSS graph PNG captured
                from the stopped PID and embedded in the confirmation email.

        Returns:
            None: The method sends the configured email when alerts are
            enabled and otherwise performs no delivery.

        Raises:
            RuntimeError: Not raised by this wrapper. Delivery errors are
            reported by :meth:`send_consolidated_status_email`.
        """
        self.send_consolidated_status_email(
            "scheduled_restart_success",
            {
                "title": title,
                "old_pid": old_pid,
                "new_pid": new_pid,
                "scheduled_restart_count": scheduled_restart_count,
                "runtime": runtime,
                "interval_seconds": interval_seconds,
                "graph_png": graph_png,
            },
        )

    def report_successful_memory_aware_scheduled_restart(
        self,
        title: str,
        old_pid: Optional[int],
        new_pid: int,
        scheduled_restart_count: int,
        runtime: float,
        current_rss_bytes: float,
        threshold_bytes: float,
        poll_interval_seconds: float,
        graph_png: Optional[bytes],
    ) -> None:
        """Report a successful restart caused by process-tree RSS threshold.

        Args:
            title (str): Human-readable monitored process title.
            old_pid (Optional[int]): PID intentionally stopped after its
                process-tree RSS met the configured threshold. ``None`` is
                displayed as unavailable when the PID was not recorded.
            new_pid (int): Replacement PID that is running and monitored.
            scheduled_restart_count (int): Number of successful scheduled
                restarts including this transition.
            runtime (float): Runtime of the stopped process in seconds.
            current_rss_bytes (float): Process-tree RSS sample in bytes that
                met or exceeded ``threshold_bytes``.
            threshold_bytes (float): Positive configured process-tree RSS
                threshold in bytes.
            poll_interval_seconds (float): Positive interval in seconds used
                to check process-tree RSS.
            graph_png (Optional[bytes]): Process-tree RSS graph PNG captured
                from the stopped PID. ``None`` sends the confirmation without
                an inline graph after graph capture failed.

        Returns:
            None: The method sends the configured email when alerts are
            enabled and otherwise performs no delivery.

        Raises:
            RuntimeError: Not raised by this wrapper. Delivery errors are
            reported by :meth:`send_consolidated_status_email`.
        """
        self.send_consolidated_status_email(
            "memory_aware_scheduled_restart_success",
            {
                "title": title,
                "old_pid": old_pid,
                "new_pid": new_pid,
                "scheduled_restart_count": scheduled_restart_count,
                "runtime": runtime,
                "current_rss_bytes": current_rss_bytes,
                "threshold_bytes": threshold_bytes,
                "poll_interval_seconds": poll_interval_seconds,
                "graph_png": graph_png,
            },
        )

    def report_task_completion(
        self,
        title: str,
        restart_count: int,
        total_runtime: float,
        scheduled_restart_count: int = 0,
    ) -> None:
        """Report that the monitored task finished successfully.

        Args:
            title (str): Human-readable monitored process title.
            restart_count (int): Number of genuine crash or failure restarts.
            total_runtime (float): Total monitored runtime in seconds.
            scheduled_restart_count (int): Number of successful scheduled
                restarts. Defaults to ``0``.

        Returns:
            None: The method sends the configured completion email when alerts
            are enabled.

        Raises:
            RuntimeError: Not raised by this wrapper. Delivery errors are
            reported by :meth:`send_consolidated_status_email`.
        """
        self.send_consolidated_status_email(
            "task_complete",
            {
                "title": title,
                "restart_count": restart_count,
                "scheduled_restart_count": scheduled_restart_count,
                "total_runtime": total_runtime,
            },
        )

    def report_final_failure(self, title: str, restart_count: int, error: str) -> None:
        """Send a final failure notification when restarts are exhausted."""
        self.send_consolidated_status_email(
            "restart_failed",
            {
                "title": title,
                "failed_attempts": restart_count,
                "remaining_attempts": 0,
                "restart_count": restart_count,
                "error": error,
            },
        )

    def report_possible_memory_leak(
        self,
        title: str,
        pid: int,
        current_rss_mib: float,
        net_growth_mib: float,
        slope_mib_per_minute: float,
        r_squared: float,
        warmup_seconds: float,
        window_seconds: float,
        graph_png: bytes,
    ) -> None:
        """Send one possible memory leak warning with an inline RAM graph.

        Args:
            title (str): Human-readable monitored process title.
            pid (int): Root PID whose process-tree RSS triggered detection.
            current_rss_mib (float): Most recent process-tree RSS in MiB.
            net_growth_mib (float): Median RSS increase across the analysis
                window in MiB.
            slope_mib_per_minute (float): Fitted RSS trend slope in MiB/min.
            r_squared (float): Coefficient of determination for the fitted
                linear trend.
            warmup_seconds (float): Initial no-check duration in seconds.
            window_seconds (float): Qualified trend-window duration in seconds.
            graph_png (bytes): Non-empty PNG bytes embedded in the warning.

        Returns:
            None: The method delegates to the consolidated email sender when
            email alerts are enabled.

        Raises:
            RuntimeError: Not raised by this wrapper. Rendering and delivery
            failures are reported by the consolidated sender.
        """
        self.send_consolidated_status_email(
            "memory_leak_warning",
            {
                "title": title,
                "pid": pid,
                "current_rss_mib": current_rss_mib,
                "net_growth_mib": net_growth_mib,
                "slope_mib_per_minute": slope_mib_per_minute,
                "r_squared": r_squared,
                "warmup_seconds": warmup_seconds,
                "window_seconds": window_seconds,
                "graph_png": graph_png,
            },
        )
